title: SocialNetworks
modelClass: Diveramkt\Miscelanious\Models\Social
list: $/diveramkt/miscelanious/models/social/columns.yaml
recordUrl: 'diveramkt/miscelanious/socialnetworks/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: '30'
showSetup: true
showCheckboxes: true
defaultSort:
    column: sort_order
    direction: desc
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
