title: Phones
modelClass: Diveramkt\Miscelanious\Models\Phone
list: $/diveramkt/miscelanious/models/phone/columns.yaml
recordUrl: 'diveramkt/miscelanious/phones/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: '30'
showSetup: true
showCheckboxes: true
defaultSort:
    column: created_at
    direction: desc
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
