plugin:
    name: 'diveramkt.miscelanious::lang.plugin.name'
    description: 'diveramkt.miscelanious::lang.plugin.description'
    author: DiveraMkt
    icon: oc-icon-asterisk
    homepage: ''
permissions:
    manage_testmonials:
        tab: 'diveramkt.miscelanious::lang.plugin.name'
        label: 'diveramkt.miscelanious::lang.testmonial.manage_testmonials'
    manage_phones:
        tab: 'diveramkt.miscelanious::lang.plugin.name'
        label: 'diveramkt.miscelanious::lang.phone.manage_phones'
    manage_social:
        tab: 'diveramkt.miscelanious::lang.plugin.name'
        label: 'diveramkt.miscelanious::lang.social.manage_social'
    manage_company:
        tab: 'diveramkt.miscelanious::lang.plugin.name'
        label: 'diveramkt.miscelanious::lang.company.mange_company'
navigation:
    miscelanious:
        label: 'diveramkt.miscelanious::lang.config.miscelanious'
        url: diveramkt/miscelanious/testmonials
        icon: icon-asterisk
        sideMenu:
            menu-testmonials:
                label: 'diveramkt.miscelanious::lang.testmonial.tesmonials'
                url: diveramkt/miscelanious/testmonials
                icon: icon-bullhorn
            menu-phones:
                label: 'diveramkt.miscelanious::lang.phone.phones'
                url: diveramkt/miscelanious/phones
                icon: icon-phone
            menu-social:
                label: 'diveramkt.miscelanious::lang.social.social_networks'
                url: diveramkt/miscelanious/socialnetworks
                icon: icon-group
            menu-company:
                label: 'diveramkt.miscelanious::lang.company.companies'
                url: diveramkt/miscelanious/companies
                icon: icon-building
