plugin:
    name: 'diveramkt.miscelanious::lang.plugin.name'
    description: 'diveramkt.miscelanious::lang.plugin.description'
    author: DiveraMkt
    icon: oc-icon-asterisk
    homepage: ''
permissions:
    manage_testmonials:
        tab: 'diveramkt.miscelanious::lang.plugin.name'
        label: 'diveramkt.miscelanious::lang.testmonial.manage_testmonials'
    manage_phones:
        tab: 'diveramkt.miscelanious::lang.plugin.name'
        label: 'diveramkt.miscelanious::lang.phone.manage_phones'
    manage_social:
        tab: 'diveramkt.miscelanious::lang.plugin.name'
        label: 'diveramkt.miscelanious::lang.social.manage_social'
    manage_company:
        tab: 'diveramkt.miscelanious::lang.plugin.name'
        label: 'diveramkt.miscelanious::lang.company.mange_company'
    manage_contacts:
        tab: 'diveramkt.miscelanious::lang.plugin.name'
        label: 'diveramkt.miscelanious::lang.contacts.manage_contacts'
    manage_parceiros:
        tab: 'diveramkt.miscelanious::lang.plugin.name'
        label: 'diveramkt.miscelanious::lang.parceiros.manage'
    manage_equipe:
        tab: 'diveramkt.miscelanious::lang.plugin.name'
        label: 'diveramkt.miscelanious::lang.equipe.manage'
    manage_miscelanious_config:
        tab: 'diveramkt.miscelanious::lang.plugin.name'
        label: 'diveramkt.miscelanious::lang.config.manage'
    manage_downloads:
        tab: 'diveramkt.miscelanious::lang.plugin.name'
        label: 'diveramkt.miscelanious::lang.downloads.manage'
    manage_content_blocks:
        tab: 'diveramkt.miscelanious::lang.plugin.name'
        label: 'Gerenciar Blocos de conteúdo'
navigation:
    miscelanious:
        label: 'diveramkt.miscelanious::lang.config.miscelanious'
        url: diveramkt/miscelanious/homeplugin
        icon: icon-asterisk
        permissions:
            - manage_testmonials
            - manage_contacts
            - manage_phones
            - manage_social
            - manage_company
            - manage_parceiros
            - manage_downloads
            - manage_content_blocks
        sideMenu:
            menu-testmonials:
                label: 'diveramkt.miscelanious::lang.testmonial.tesmonials'
                url: diveramkt/miscelanious/testmonials
                icon: icon-bullhorn
                permissions:
                    - manage_testmonials
            side-menu-contacts:
                label: 'diveramkt.miscelanious::lang.contacts.contacts'
                url: diveramkt/miscelanious/contacts
                icon: icon-phone
                permissions:
                    - manage_contacts
            menu-phones:
                label: 'diveramkt.miscelanious::lang.phone.phones'
                url: diveramkt/miscelanious/phones
                icon: icon-phone
                permissions:
                    - manage_phones
            menu-social:
                label: 'diveramkt.miscelanious::lang.social.social_networks'
                url: diveramkt/miscelanious/socialnetworks
                icon: icon-group
                permissions:
                    - manage_social
            menu-company:
                label: 'diveramkt.miscelanious::lang.company.companies'
                url: diveramkt/miscelanious/companies
                icon: icon-building
                permissions:
                    - manage_company
            miscelanious-parceiros:
                label: 'diveramkt.miscelanious::lang.parceiros.name'
                url: diveramkt/miscelanious/parceiros
                icon: icon-thumbs-up
                permissions:
                    - manage_parceiros
            miscelanious:
                label: 'diveramkt.miscelanious::lang.equipe.name'
                url: diveramkt/miscelanious/equipecategorias
                icon: icon-users
                permissions:
                    - manage_equipe
            menu-downloads:
                label: 'diveramkt.miscelanious::lang.downloads.name'
                url: diveramkt/miscelanious/downloads
                icon: icon-file-pdf-o
                permissions:
                    - manage_downloads
            miscelanious-content-blocks:
                label: 'Blocos de conteúdo'
                url: diveramkt/miscelanious/contentblocks
                icon: icon-file-text
                permissions:
                    - manage_content_blocks
