list: $/diveramkt/miscelanious/models/download/columns.yaml
modelClass: Diveramkt\Miscelanious\Models\Download
title: Downloads
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'diveramkt/miscelanious/downloads/update/:id'
