title: Companies
modelClass: Diveramkt\Miscelanious\Models\Company
list: $/diveramkt/miscelanious/models/company/columns.yaml
recordUrl: diveramkt/miscelanious/companies/update/1
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 20
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
