name: Companies
modelClass: Diveramkt\Miscelanious\Models\Company
form: $/diveramkt/miscelanious/models/company/fields.yaml
defaultRedirect: diveramkt/miscelanious/companies/update/1
create:
    redirect: diveramkt/miscelanious/companies/update/1
    redirectClose: diveramkt/miscelanious/companies/update/1
update:
    redirect: diveramkt/miscelanious/companies/update/1
    redirectClose: diveramkt/miscelanious/companies/update/1
