list: $/diveramkt/miscelanious/models/contentblocks/columns.yaml
modelClass: Diveramkt\Miscelanious\Models\Contentblocks
title: Contentblocks
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'diveramkt/miscelanious/contentblocks/update/:id'
