list: $/diveramkt/miscelanious/models/contact/columns.yaml
modelClass: Diveramkt\Miscelanious\Models\Contact
title: Contacts
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'diveramkt/miscelanious/contacts/update/:id'
